### ISSUE TITLE
Broken player client side health.

### ISSUE THREAD

**Issue by H3xtyy** [NoahvdAa/HealthHider#1]
Hi, there is a bug in a plugin, players see only half a heart if they take damage.
Server: Purpur
Version: 1.19.3
https://streamable.com/udascp

**Comment by Gracv** [comment]
https://streamable.com/udascp

**Comment by NoahvdAa** [comment]
Sorry for the long wait, should be fixed in f272efa, a release will be out shortly, not sure how I managed to miss this during testing 😅
